package com.televisory.capitalmarket.util;

import java.util.HashMap;
import java.util.Map;

import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFPalette;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.apache.poi.xssf.usermodel.XSSFColor;
import org.apache.poi.xssf.usermodel.XSSFFont;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

public class ExcelStyleUtil {

	public static Map<String, CellStyle> getAllStyles(XSSFWorkbook workbook) {		

	
	    /*HSSFPalette palette = workbook.get
		palette.setColorAtIndex(HSSFColor.BLUE.index, (byte) 32, (byte) 55, (byte) 100);
		palette.setColorAtIndex(HSSFColor.LIGHT_BLUE.index, (byte) 47, (byte) 117, (byte) 181);
		palette.setColorAtIndex(HSSFColor.SKY_BLUE.index, (byte) 189, (byte) 215, (byte) 238);
		palette.setColorAtIndex(HSSFColor.GREY_25_PERCENT.index, (byte) 237, (byte) 237, (byte) 237);
		palette.setColorAtIndex(HSSFColor.DARK_BLUE.index, (byte) 32, (byte) 55, (byte) 100);*/


		Map<String, CellStyle> mapStyles = new HashMap<>();

		XSSFFont LIGHT_BLUE_WITH_HEIGHT = workbook.createFont();
		LIGHT_BLUE_WITH_HEIGHT.setColor(HSSFColor.LIGHT_BLUE.index);
		LIGHT_BLUE_WITH_HEIGHT.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
		LIGHT_BLUE_WITH_HEIGHT.setFontHeight((short) (7.5 * 30));

		XSSFFont LIGHT_BLUE = workbook.createFont();
		LIGHT_BLUE.setColor(HSSFColor.LIGHT_BLUE.index);
		LIGHT_BLUE.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);

		XSSFFont LIGHT_BLUE_UNDERLINE = workbook.createFont();
		LIGHT_BLUE_UNDERLINE.setColor(HSSFColor.LIGHT_BLUE.index);
		LIGHT_BLUE_UNDERLINE.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
		LIGHT_BLUE_UNDERLINE.setUnderline(HSSFFont.U_SINGLE);

		XSSFFont BROWN_WITHOUT_HEIGHT = workbook.createFont();
		BROWN_WITHOUT_HEIGHT.setColor(HSSFColor.BROWN.index);
		BROWN_WITHOUT_HEIGHT.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);

		XSSFFont WHITE_WITHOUT_HEIGHT = workbook.createFont();
		WHITE_WITHOUT_HEIGHT.setColor(HSSFColor.WHITE.index);
		WHITE_WITHOUT_HEIGHT.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);

		XSSFFont BOLD_FONT = workbook.createFont();
		BOLD_FONT.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);

		XSSFCellStyle BORDER_ALL = workbook.createCellStyle();
		BORDER_ALL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_ALL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_ALL.setBorderTop(HSSFCellStyle.BORDER_THIN);
		BORDER_ALL.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_ALL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_ALL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BORDER_ALL", BORDER_ALL);

		XSSFCellStyle BORDER_TOP = workbook.createCellStyle();
		BORDER_TOP.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_TOP.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_TOP.setBorderTop(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BORDER_TOP", BORDER_TOP);

		XSSFCellStyle BORDER_BOTTOM_LEFT_RIGHT = workbook.createCellStyle();
		//BORDER_BOTTOM_LEFT_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_BOTTOM_LEFT_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_BOTTOM_LEFT_RIGHT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		mapStyles.put("BORDER_BOTTOM_LEFT_RIGHT", BORDER_BOTTOM_LEFT_RIGHT);

		XSSFCellStyle BORDER_LEFT = workbook.createCellStyle();
		//BORDER_LEFT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_LEFT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_LEFT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BORDER_LEFT", BORDER_LEFT);

		XSSFCellStyle BORDER_LEFT_BLUE_FONT = workbook.createCellStyle();
		BORDER_LEFT_BLUE_FONT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_LEFT_BLUE_FONT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_LEFT_BLUE_FONT.setBorderLeft(HSSFCellStyle.BORDER_THIN);		
		BORDER_LEFT_BLUE_FONT.setFont(LIGHT_BLUE_WITH_HEIGHT);
		mapStyles.put("BORDER_LEFT_BLUE_FONT", BORDER_LEFT_BLUE_FONT);

		XSSFCellStyle BORDER_RIGHT = workbook.createCellStyle();
		/*BORDER_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);*/
		//BORDER_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_RIGHT.setAlignment(HSSFCellStyle.ALIGN_RIGHT);			
		mapStyles.put("BORDER_RIGHT", BORDER_RIGHT);

		XSSFCellStyle BORDER_TOP_LEFT = workbook.createCellStyle();
		BORDER_TOP_LEFT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_TOP_LEFT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_TOP_LEFT.setBorderTop(HSSFCellStyle.BORDER_THIN);
		BORDER_TOP_LEFT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BORDER_TOP_LEFT", BORDER_TOP_LEFT);


		XSSFCellStyle BORDER_TOP_LEFT_BLUE_FONT = workbook.createCellStyle();
		BORDER_TOP_LEFT_BLUE_FONT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_TOP_LEFT_BLUE_FONT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_TOP_LEFT_BLUE_FONT.setBorderTop(HSSFCellStyle.BORDER_THIN);
		BORDER_TOP_LEFT_BLUE_FONT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		LIGHT_BLUE_WITH_HEIGHT = workbook.createFont();
		LIGHT_BLUE_WITH_HEIGHT.setColor(HSSFColor.LIGHT_BLUE.index);
		LIGHT_BLUE_WITH_HEIGHT.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
		LIGHT_BLUE_WITH_HEIGHT.setFontHeight((short) (7.5 * 30));
		BORDER_TOP_LEFT_BLUE_FONT.setFont(LIGHT_BLUE_WITH_HEIGHT);
		mapStyles.put("BORDER_TOP_LEFT_BLUE_FONT", BORDER_TOP_LEFT_BLUE_FONT);

		XSSFCellStyle BORDER_BUTTOM_LEFT = workbook.createCellStyle();
		BORDER_BUTTOM_LEFT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_BUTTOM_LEFT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_BUTTOM_LEFT.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BUTTOM_LEFT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BORDER_BUTTOM_LEFT", BORDER_BUTTOM_LEFT);

		XSSFCellStyle BORDER_BUTTOM_LEFT_BLUE_FONT = workbook.createCellStyle();
		BORDER_BUTTOM_LEFT_BLUE_FONT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_BUTTOM_LEFT_BLUE_FONT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_BUTTOM_LEFT_BLUE_FONT.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BUTTOM_LEFT_BLUE_FONT.setBorderLeft(HSSFCellStyle.BORDER_THIN);

		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
		font.setFontHeight((short) (7.5 * 30));*/
		BORDER_BUTTOM_LEFT_BLUE_FONT.setFont(LIGHT_BLUE_WITH_HEIGHT);
		mapStyles.put("BORDER_BUTTOM_LEFT_BLUE_FONT", BORDER_BUTTOM_LEFT_BLUE_FONT);


		/* Headers */
		XSSFCellStyle HEADER1_WITHOUT_BORDER = workbook.createCellStyle();
		HEADER1_WITHOUT_BORDER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER1_WITHOUT_BORDER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
		font.setFontHeight((short) (7.5 * 30));*/
		HEADER1_WITHOUT_BORDER.setFont(LIGHT_BLUE_WITH_HEIGHT);
		mapStyles.put("HEADER1_WITHOUT_BORDER", HEADER1_WITHOUT_BORDER);

		XSSFCellStyle HEADER1_WITH_BORDER_LEFT_RIGHT_TOP = workbook.createCellStyle();
		HEADER1_WITH_BORDER_LEFT_RIGHT_TOP.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER1_WITH_BORDER_LEFT_RIGHT_TOP.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER1_WITH_BORDER_LEFT_RIGHT_TOP.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		HEADER1_WITH_BORDER_LEFT_RIGHT_TOP.setBorderRight(HSSFCellStyle.BORDER_THIN);
		HEADER1_WITH_BORDER_LEFT_RIGHT_TOP.setBorderTop(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
		font.setFontHeight((short) (7.5 * 30));*/
		HEADER1_WITH_BORDER_LEFT_RIGHT_TOP.setFont(LIGHT_BLUE_WITH_HEIGHT);
		mapStyles.put("HEADER1_WITH_BORDER_LEFT_RIGHT_TOP", HEADER1_WITH_BORDER_LEFT_RIGHT_TOP);

		XSSFCellStyle HEADER1_WITH_BORDER_BOTTOM = workbook.createCellStyle();
		HEADER1_WITH_BORDER_BOTTOM.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER1_WITH_BORDER_BOTTOM.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER1_WITH_BORDER_BOTTOM.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
		font.setFontHeight((short) (7.5 * 30));*/
		HEADER1_WITH_BORDER_BOTTOM.setFont(LIGHT_BLUE_WITH_HEIGHT);
		HEADER1_WITH_BORDER_BOTTOM.setVerticalAlignment(HSSFCellStyle.VERTICAL_BOTTOM);
		mapStyles.put("HEADER1_WITH_BORDER_BOTTOM", HEADER1_WITH_BORDER_BOTTOM);


		XSSFCellStyle BORDER_BUTTOM_RIGHT = workbook.createCellStyle();
		BORDER_BUTTOM_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_BUTTOM_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_BUTTOM_RIGHT.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BUTTOM_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BORDER_BUTTOM_RIGHT", BORDER_BUTTOM_RIGHT);


		XSSFCellStyle BLUE_FONT = workbook.createCellStyle();
		BLUE_FONT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BLUE_FONT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
		font.setFontHeight((short) (7.5 * 30));*/
		BLUE_FONT.setFont(LIGHT_BLUE_WITH_HEIGHT);
		mapStyles.put("BLUE_FONT", BLUE_FONT);

		XSSFCellStyle BLUE_FONT_WITHOUT_BACKGROUND = workbook.createCellStyle();
		BLUE_FONT_WITHOUT_BACKGROUND.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		/*BLUE_FONT_WITHOUT_BACKGROUND.setBorderTop(HSSFCellStyle.BORDER_THIN);
		BLUE_FONT_WITHOUT_BACKGROUND.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BLUE_FONT_WITHOUT_BACKGROUND.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BLUE_FONT_WITHOUT_BACKGROUND.setBorderRight(HSSFCellStyle.BORDER_THIN);*/
		//BLUE_FONT_WITHOUT_BACKGROUND.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
		font.setFontHeight((short) (7.5 * 30));*/
		BLUE_FONT_WITHOUT_BACKGROUND.setFont(LIGHT_BLUE_WITH_HEIGHT);
		mapStyles.put("BLUE_FONT_WITHOUT_BACKGROUND", BLUE_FONT_WITHOUT_BACKGROUND);

		XSSFCellStyle BORDER_TOP_RIGHT = workbook.createCellStyle();
		BORDER_TOP_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_TOP_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_TOP_RIGHT.setBorderTop(HSSFCellStyle.BORDER_THIN);
		BORDER_TOP_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BORDER_TOP_RIGHT", BORDER_TOP_RIGHT);

		XSSFCellStyle BORDER_LEFT_RIGHT = workbook.createCellStyle();
		//BORDER_LEFT_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_LEFT_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_LEFT_RIGHT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BORDER_LEFT_RIGHT", BORDER_LEFT_RIGHT);

		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM", BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM);

		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setFillForegroundColor(new XSSFColor(new java.awt.Color(32, 55, 100)));
		  // and solid fill pattern produces solid grey cell fill
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setFillPattern(FillPatternType.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setBorderTop(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setBorderRight(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.WHITE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/

		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setFont(WHITE_WITHOUT_HEIGHT);		
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setWrapText(true);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setAlignment(HSSFCellStyle.ALIGN_CENTER);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER", BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER);

		XSSFCellStyle BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM = workbook.createCellStyle();
		BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM.setAlignment(HSSFCellStyle.ALIGN_RIGHT);
		mapStyles.put("BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM", BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM);


		XSSFCellStyle HEADER2_WITH_BORDER_ALL_CENTER = workbook.createCellStyle();
		HEADER2_WITH_BORDER_ALL_CENTER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER2_WITH_BORDER_ALL_CENTER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER2_WITH_BORDER_ALL_CENTER.setBorderTop(HSSFCellStyle.BORDER_THIN);
		HEADER2_WITH_BORDER_ALL_CENTER.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		HEADER2_WITH_BORDER_ALL_CENTER.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		HEADER2_WITH_BORDER_ALL_CENTER.setBorderRight(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/
		HEADER2_WITH_BORDER_ALL_CENTER.setFont(LIGHT_BLUE);
		HEADER2_WITH_BORDER_ALL_CENTER.setAlignment(HSSFCellStyle.ALIGN_CENTER);
		HEADER2_WITH_BORDER_ALL_CENTER.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		mapStyles.put("HEADER2_WITH_BORDER_ALL_CENTER", HEADER2_WITH_BORDER_ALL_CENTER);


		XSSFCellStyle HEADER2_WITH_BORDER_RIGHT_TOP_BOTTOM_CENTER = workbook.createCellStyle();
		HEADER2_WITH_BORDER_RIGHT_TOP_BOTTOM_CENTER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
	//	HEADER2_WITH_BORDER_RIGHT_TOP_BOTTOM_CENTER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER2_WITH_BORDER_RIGHT_TOP_BOTTOM_CENTER.setBorderTop(HSSFCellStyle.BORDER_THIN);
		HEADER2_WITH_BORDER_RIGHT_TOP_BOTTOM_CENTER.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		HEADER2_WITH_BORDER_RIGHT_TOP_BOTTOM_CENTER.setBorderRight(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/
		HEADER2_WITH_BORDER_RIGHT_TOP_BOTTOM_CENTER.setFont(LIGHT_BLUE);
		HEADER2_WITH_BORDER_RIGHT_TOP_BOTTOM_CENTER.setAlignment(HSSFCellStyle.ALIGN_CENTER);
		mapStyles.put("HEADER2_WITH_BORDER_RIGHT_TOP_BOTTOM_CENTER", HEADER2_WITH_BORDER_RIGHT_TOP_BOTTOM_CENTER);


		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_CENTER = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_CENTER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_CENTER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_CENTER.setAlignment(HSSFCellStyle.ALIGN_CENTER);
		BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_CENTER.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_CENTER.setBorderRight(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_CENTER", BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_CENTER);

		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_TOP_CENTER = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_TOP_CENTER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_TOP_CENTER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_TOP_CENTER.setAlignment(HSSFCellStyle.ALIGN_CENTER);
		BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_TOP_CENTER.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_TOP_CENTER.setBorderRight(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_TOP_CENTER", BLACK_TEXT_GRAY_BACKGROUND_WITH_BORDER_LEFT_RIGHT_TOP_CENTER);

		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT", BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT);

		XSSFCellStyle BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT = workbook.createCellStyle();
		BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT.setAlignment(HSSFCellStyle.ALIGN_RIGHT);
		mapStyles.put("BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT", BLACK_TEXT_RIGHT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT);


		XSSFCellStyle HEADER2_WITH_BORDER_LEFT_RIGHT = workbook.createCellStyle();
		HEADER2_WITH_BORDER_LEFT_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER2_WITH_BORDER_LEFT_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER2_WITH_BORDER_LEFT_RIGHT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		HEADER2_WITH_BORDER_LEFT_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/
		HEADER2_WITH_BORDER_LEFT_RIGHT.setFont(LIGHT_BLUE);
		mapStyles.put("HEADER2_WITH_BORDER_LEFT_RIGHT", HEADER2_WITH_BORDER_LEFT_RIGHT);


		XSSFCellStyle DARK_BLUE_BACKGROUND = workbook.createCellStyle();
		DARK_BLUE_BACKGROUND.setFillForegroundColor(HSSFColor.DARK_BLUE.index);
		//DARK_BLUE_BACKGROUND.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		DARK_BLUE_BACKGROUND.setAlignment(HSSFCellStyle.ALIGN_CENTER);
		mapStyles.put("DARK_BLUE_BACKGROUND", DARK_BLUE_BACKGROUND);

		XSSFCellStyle HEADER2_WITH_BORDER_TOP_BOTTOM_CENTER = workbook.createCellStyle();
		HEADER2_WITH_BORDER_TOP_BOTTOM_CENTER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER2_WITH_BORDER_TOP_BOTTOM_CENTER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER2_WITH_BORDER_TOP_BOTTOM_CENTER.setBorderTop(HSSFCellStyle.BORDER_THIN);
		HEADER2_WITH_BORDER_TOP_BOTTOM_CENTER.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/
		HEADER2_WITH_BORDER_TOP_BOTTOM_CENTER.setFont(LIGHT_BLUE);
		HEADER2_WITH_BORDER_TOP_BOTTOM_CENTER.setAlignment(HSSFCellStyle.ALIGN_CENTER);
		mapStyles.put("HEADER2_WITH_BORDER_TOP_BOTTOM_CENTER", HEADER2_WITH_BORDER_TOP_BOTTOM_CENTER);




		//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////		

		XSSFCellStyle HEADER2_WITHOUT_BORDER = workbook.createCellStyle();
		HEADER2_WITHOUT_BORDER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER2_WITHOUT_BORDER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/
		HEADER2_WITHOUT_BORDER.setFont(LIGHT_BLUE);
		mapStyles.put("HEADER2_WITHOUT_BORDER", HEADER2_WITHOUT_BORDER);

		XSSFCellStyle HEADER2_WITH_BORDER_LEFT = workbook.createCellStyle();
		HEADER2_WITH_BORDER_LEFT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER2_WITH_BORDER_LEFT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER2_WITH_BORDER_LEFT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		/*	font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/
		HEADER2_WITH_BORDER_LEFT.setFont(LIGHT_BLUE);
		mapStyles.put("HEADER2_WITH_BORDER_LEFT", HEADER2_WITH_BORDER_LEFT);








		XSSFCellStyle HEADER2_WITH_BORDER_TOP_CENTER = workbook.createCellStyle();
		HEADER2_WITH_BORDER_TOP_CENTER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER2_WITH_BORDER_TOP_CENTER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER2_WITH_BORDER_TOP_CENTER.setBorderTop(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/
		HEADER2_WITH_BORDER_TOP_CENTER.setFont(LIGHT_BLUE);
		HEADER2_WITH_BORDER_TOP_CENTER.setAlignment(HSSFCellStyle.ALIGN_CENTER);
		mapStyles.put("HEADER2_WITH_BORDER_TOP_CENTER", HEADER2_WITH_BORDER_TOP_CENTER);



		XSSFCellStyle HEADER2_WITH_BORDER_BOTTOM = workbook.createCellStyle();
		HEADER2_WITH_BORDER_BOTTOM.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER2_WITH_BORDER_BOTTOM.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER2_WITH_BORDER_BOTTOM.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/
		HEADER2_WITH_BORDER_BOTTOM.setFont(LIGHT_BLUE);
		mapStyles.put("HEADER2_WITH_BORDER_BOTTOM", HEADER2_WITH_BORDER_BOTTOM);

		XSSFCellStyle HEADER2_WITH_BORDER_ALL = workbook.createCellStyle();
		HEADER2_WITH_BORDER_ALL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		HEADER2_WITH_BORDER_ALL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER2_WITH_BORDER_ALL.setBorderTop(HSSFCellStyle.BORDER_THIN);
		HEADER2_WITH_BORDER_ALL.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		HEADER2_WITH_BORDER_ALL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		HEADER2_WITH_BORDER_ALL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/
		HEADER2_WITH_BORDER_ALL.setFont(LIGHT_BLUE);
		mapStyles.put("HEADER2_WITH_BORDER_ALL", HEADER2_WITH_BORDER_ALL);



		XSSFCellStyle HEADER2_UNDERLINE_WITH_BORDER_LEFT_RIGHT = workbook.createCellStyle();
		HEADER2_UNDERLINE_WITH_BORDER_LEFT_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//HEADER2_UNDERLINE_WITH_BORDER_LEFT_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER2_UNDERLINE_WITH_BORDER_LEFT_RIGHT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		HEADER2_UNDERLINE_WITH_BORDER_LEFT_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.LIGHT_BLUE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
		font.setUnderline(HSSFFont.U_SINGLE);*/
		HEADER2_UNDERLINE_WITH_BORDER_LEFT_RIGHT.setFont(LIGHT_BLUE_UNDERLINE);
		mapStyles.put("HEADER2_UNDERLINE_WITH_BORDER_LEFT_RIGHT", HEADER2_UNDERLINE_WITH_BORDER_LEFT_RIGHT);


		/* Header2 End */

		/* Black Text Start */
		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setFillForegroundColor(new XSSFColor(new java.awt.Color(32, 55, 100)));
		  // and solid fill pattern produces solid grey cell fill
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_BUTTOM_CENTER.setFillPattern(FillPatternType.SOLID_FOREGROUND);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER", BLACK_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER);

		XSSFCellStyle NUMBER_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER = workbook.createCellStyle();
		NUMBER_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		NUMBER_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		NUMBER_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER.setDataFormat(workbook.createDataFormat().getFormat("0.0"));
		NUMBER_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER.setAlignment(CellStyle.ALIGN_RIGHT);
		mapStyles.put("NUMBER_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER", NUMBER_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER);

		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER_CENTER = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER_CENTER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BLACK_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER_CENTER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER_CENTER.setAlignment(HSSFCellStyle.ALIGN_CENTER);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER_CENTER", BLACK_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER_CENTER);

		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP_THICK = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP_THICK.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP_THICK.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP_THICK.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP_THICK.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP_THICK.setBorderTop(HSSFCellStyle.BORDER_DASHED);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP_THICK", BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP_THICK);

		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP.setBorderTop(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP", BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_RIGHT_TOP);

		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP.setBorderTop(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP", BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP);

		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP_WRAP = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP_WRAP.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP_WRAP.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP_WRAP.setBorderTop(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP_WRAP.setWrapText(true);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP_WRAP.setVerticalAlignment(HSSFCellStyle.VERTICAL_TOP);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP_WRAP", BLACK_TEXT_GRAY_BACKGROUND_BORDER_TOP_WRAP);




		XSSFCellStyle BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_TOP = workbook.createCellStyle();
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_TOP.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_TOP.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_TOP.setBorderTop(HSSFCellStyle.BORDER_THIN);
		BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_TOP.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		mapStyles.put("BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_TOP", BLACK_TEXT_GRAY_BACKGROUND_BORDER_LEFT_TOP);


		XSSFCellStyle BROWN_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER = workbook.createCellStyle();
		BROWN_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BROWN_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.BROWN.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/
		BROWN_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER.setFont(BROWN_WITHOUT_HEIGHT);
		BROWN_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER.setWrapText(true);
		BROWN_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER.setVerticalAlignment(HSSFCellStyle.VERTICAL_BOTTOM);
		//BROWN_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER.setBorderBottom(HSSFCellStyle.BORDER_MEDIUM);
		mapStyles.put("BROWN_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER", BROWN_TEXT_GRAY_BACKGROUND_WITHOUT_BORDER);
		/* Black Text End */


		//NEW STYLES ADDED 02112018

		XSSFCellStyle HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND = workbook.createCellStyle();
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND.setFillForegroundColor(HSSFColor.BLUE.index);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND.setBorderTop(HSSFCellStyle.BORDER_THIN);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND.setBorderRight(HSSFCellStyle.BORDER_THIN);
		/*font = workbook.createFont();
		font.setColor(HSSFColor.WHITE.index);
		font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);*/

		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND.setFont(WHITE_WITHOUT_HEIGHT);		
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND.setWrapText(true);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND.setAlignment(HSSFCellStyle.ALIGN_CENTER);		
		mapStyles.put("HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND", HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND);

		///////////// Added By NC ////////


		XSSFCellStyle HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER = workbook.createCellStyle();
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setFillForegroundColor(HSSFColor.BLUE.index);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setBottomBorderColor(IndexedColors.WHITE.getIndex());
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setLeftBorderColor(IndexedColors.WHITE.getIndex());	
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setRightBorderColor(IndexedColors.WHITE.getIndex());	
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setTopBorderColor(IndexedColors.WHITE.getIndex());
		
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setBorderTop(HSSFCellStyle.BORDER_THIN);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setBorderRight(HSSFCellStyle.BORDER_THIN);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setFont(WHITE_WITHOUT_HEIGHT);		
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setWrapText(true);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER.setAlignment(HSSFCellStyle.ALIGN_CENTER);	
		
			
		mapStyles.put("HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER", HEADER_WHITE_TEXT_DARK_BLUE_BACKGROUND_WHITE_BORDER);



		///////

		XSSFCellStyle BORDER_LEFT_RIGHT_ALIGN_RIGHT = workbook.createCellStyle();
	/*	BORDER_LEFT_RIGHT_ALIGN_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_LEFT_RIGHT_ALIGN_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_LEFT_RIGHT_ALIGN_RIGHT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_ALIGN_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_ALIGN_RIGHT.setAlignment(HSSFCellStyle.ALIGN_RIGHT);
		mapStyles.put("BORDER_LEFT_RIGHT_ALIGN_RIGHT", BORDER_LEFT_RIGHT_ALIGN_RIGHT);

		XSSFCellStyle BORDER_LEFT_RIGHT_ALIGN_LEFT = workbook.createCellStyle();
	/*	BORDER_LEFT_RIGHT_ALIGN_LEFT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_LEFT_RIGHT_ALIGN_LEFT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_LEFT_RIGHT_ALIGN_LEFT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_ALIGN_LEFT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_ALIGN_LEFT.setAlignment(HSSFCellStyle.ALIGN_LEFT);
		mapStyles.put("BORDER_LEFT_RIGHT_ALIGN_LEFT", BORDER_LEFT_RIGHT_ALIGN_LEFT);
		
		XSSFCellStyle BORDER_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL = workbook.createCellStyle();
		BORDER_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		//BORDER_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);
		BORDER_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setWrapText(true);
		mapStyles.put("BORDER_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL", BORDER_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL);

		XSSFCellStyle BORDER_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL = workbook.createCellStyle();
		BORDER_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		//BORDER_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setAlignment(HSSFCellStyle.ALIGN_LEFT);
		//BORDER_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setWrapText(true);
		mapStyles.put("BORDER_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL", BORDER_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL);

		XSSFCellStyle BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT = workbook.createCellStyle();
		/*BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT.setAlignment(HSSFCellStyle.ALIGN_LEFT);	
		mapStyles.put("BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT", BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT);

		XSSFCellStyle BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT = workbook.createCellStyle();
		/*BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT.setAlignment(HSSFCellStyle.ALIGN_RIGHT);	
		mapStyles.put("BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT", BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT);
		
		XSSFCellStyle BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL = workbook.createCellStyle();
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		//BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		//BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setAlignment(HSSFCellStyle.ALIGN_LEFT);
		//BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL.setWrapText(true);
		mapStyles.put("BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL", BORDER_BOTTOM_LEFT_RIGHT_ALIGN_LEFT_LARGE_CELL);

		XSSFCellStyle BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL = workbook.createCellStyle();
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		//BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		//BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);	
		//BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL.setWrapText(true);
		mapStyles.put("BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL", BORDER_BOTTOM_LEFT_RIGHT_ALIGN_RIGHT_LARGE_CELL);




		XSSFCellStyle BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL = workbook.createCellStyle();
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,##0.00"));
		/*BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);
		mapStyles.put("BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL", BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL);
		
		
		
		
		XSSFCellStyle BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL = workbook.createCellStyle();
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,##0.000"));
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);
		mapStyles.put("BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL", BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL);



		XSSFCellStyle BORDER_RIGHT_NUMBER_FORMAT_TWO_DECIMAL= workbook.createCellStyle();
		BORDER_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,##0.00"));
		BORDER_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);	
		mapStyles.put("BORDER_RIGHT_NUMBER_FORMAT_TWO_DECIMAL", BORDER_RIGHT_NUMBER_FORMAT_TWO_DECIMAL);
		
		XSSFCellStyle BORDER_RIGHT_NUMBER_FORMAT_THREE_DECIMAL= workbook.createCellStyle();
		BORDER_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,##0.000"));
		BORDER_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);	
		mapStyles.put("BORDER_RIGHT_NUMBER_FORMAT_THREE_DECIMAL", BORDER_RIGHT_NUMBER_FORMAT_THREE_DECIMAL);


		XSSFCellStyle BORDER_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL = workbook.createCellStyle();
	/*	BORDER_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,##0.00"));
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);*/
		/*BORDER_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);	
		mapStyles.put("BORDER_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL", BORDER_LEFT_RIGHT_NUMBER_FORMAT_TWO_DECIMAL);
		
		
		
		XSSFCellStyle BORDER_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL = workbook.createCellStyle();
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,##0.000"));
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);	
		mapStyles.put("BORDER_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL", BORDER_LEFT_RIGHT_NUMBER_FORMAT_THREE_DECIMAL);


		XSSFCellStyle HEADER_WHITE_TEXT_BLACK_BACKGROUND = workbook.createCellStyle();
		HEADER_WHITE_TEXT_BLACK_BACKGROUND.setFillForegroundColor(HSSFColor.BLACK.index);
		HEADER_WHITE_TEXT_BLACK_BACKGROUND.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);

		HEADER_WHITE_TEXT_BLACK_BACKGROUND.setFont(WHITE_WITHOUT_HEIGHT);		
		HEADER_WHITE_TEXT_BLACK_BACKGROUND.setWrapText(true);
		HEADER_WHITE_TEXT_BLACK_BACKGROUND.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		HEADER_WHITE_TEXT_BLACK_BACKGROUND.setAlignment(HSSFCellStyle.ALIGN_LEFT);		
		mapStyles.put("HEADER_WHITE_TEXT_BLACK_BACKGROUND", HEADER_WHITE_TEXT_BLACK_BACKGROUND);


		XSSFCellStyle BORDER_LEFT_RIGHT_BOLD_FONT = workbook.createCellStyle();
		BORDER_LEFT_RIGHT_BOLD_FONT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		//BORDER_LEFT_RIGHT_BOLD_FONT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_LEFT_RIGHT_BOLD_FONT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_BOLD_FONT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_BOLD_FONT.setFont(BOLD_FONT);
		mapStyles.put("BORDER_LEFT_RIGHT_BOLD_FONT", BORDER_LEFT_RIGHT_BOLD_FONT);


		XSSFCellStyle BORDER_BOTTOM_LEFT_RIGHT_BOLD_FONT = workbook.createCellStyle();
	/*	BORDER_BOTTOM_LEFT_RIGHT_BOLD_FONT.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_BOTTOM_LEFT_RIGHT_BOLD_FONT.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_BOTTOM_LEFT_RIGHT_BOLD_FONT.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_BOLD_FONT.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_BOLD_FONT.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_BOLD_FONT.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		BORDER_BOTTOM_LEFT_RIGHT_BOLD_FONT.setFont(BOLD_FONT);
		mapStyles.put("BORDER_BOTTOM_LEFT_RIGHT_BOLD_FONT", BORDER_BOTTOM_LEFT_RIGHT_BOLD_FONT);

		//FOR ONE DECIMAL

		XSSFCellStyle BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL = workbook.createCellStyle();
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,###.0"));
		/*BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);
		mapStyles.put("BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL", BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL);



		XSSFCellStyle BORDER_RIGHT_NUMBER_FORMAT_ONE_DECIMAL= workbook.createCellStyle();
		BORDER_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,###.0"));
		BORDER_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);	
		mapStyles.put("BORDER_RIGHT_NUMBER_FORMAT_ONE_DECIMAL", BORDER_RIGHT_NUMBER_FORMAT_ONE_DECIMAL);


		XSSFCellStyle BORDER_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL = workbook.createCellStyle();
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,###.0"));
		/*BORDER_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);	
		mapStyles.put("BORDER_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL", BORDER_LEFT_RIGHT_NUMBER_FORMAT_ONE_DECIMAL);


		XSSFCellStyle BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL = workbook.createCellStyle();
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,###"));
	/*	BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);*/
		/*BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setBorderBottom(HSSFCellStyle.BORDER_THIN);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setVerticalAlignment(HSSFCellStyle.VERTICAL_CENTER);
		BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);
		mapStyles.put("BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL", BORDER_BOTTOM_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL);



		XSSFCellStyle BORDER_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL= workbook.createCellStyle();
		BORDER_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,###"));
		BORDER_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		BORDER_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
		BORDER_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);	
		mapStyles.put("BORDER_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL", BORDER_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL);

		XSSFCellStyle BORDER_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL = workbook.createCellStyle();
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setDataFormat(workbook.createDataFormat().getFormat("#,###"));
		//BORDER_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setFillForegroundColor(HSSFColor.GREY_25_PERCENT.index);
		/*BORDER_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);*/
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setBorderLeft(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setBorderRight(HSSFCellStyle.BORDER_THIN);
		BORDER_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL.setAlignment(HSSFCellStyle.ALIGN_RIGHT);	
		mapStyles.put("BORDER_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL", BORDER_LEFT_RIGHT_NUMBER_FORMAT_ZERO_DECIMAL);


		return mapStyles;
	}

}
